# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171229_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 1, 49, 20, 131766, tzinfo=utc)),
        ),
    ]
